[project]
name = "summarize-meeting"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyannote-audio>=4.0.2",
    "python-dotenv>=1.2.1",
    "torchcodec==0.7.0",
]
